title: Stackbit Fresh Theme
baseURL: /
params:
  footer:
    content: '&copy; Mark Scott. All rights reserved.'
    links: []
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: /images/20190312_122408-removebg.png
    tagline: Header Tagline
    title: PhxDev
  layout_style: overflow
  palette: orange
disableKinds:
  - RSS
