title: PhxDev | Mark Scott
baseURL: https://phxdev.me/
params:
  footer:
    content: '&copy; Mark Scott. All rights reserved.'
    links: []
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: /images/20190312_122408-removebg.png
    tagline: 'I drink beer, I write code.'
    title: PhxDev
  layout_style: overflow
  palette: orange
menu:
  main: []
disableKinds:
  - RSS
enableInlineShortcodes: false
markup:
  goldmark:
    renderer:
      unsafe: true
