title: PhxDev | Mark Scott
baseURL: https://phxdev.me/
params:
  footer:
    content: "Mark Scott. All rights reserved. <br/>"
    links:
      - new_window: true
        text: Twitter
        url: https://twitter.com/phxdev
      - new_window: true
        text: YouTube
        url: https://youtube.com/c/phxdev
      - new_window: true
        text: LinkedIn
        url: https://www.linkedin.com/in/phxdev/
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: /images/headshot.webp
    tagline: I drink beer, I write code.
    title: PhxDev
  layout_style: overflow
  palette: orange
menu:
  main: []
disableKinds:
  - RSS
enableInlineShortcodes: false
markup:
  goldmark:
    renderer:
      unsafe: true
