[build]
publish = "public"
[[ redirects ]]
  from = "/youtube"
  to = "https://www.youtube.com/phxdev"
  status = 301
[[ redirects ]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/phxdev/"
  status = 301
 [[ redirects ]]
  from = "/twitter"
  to = "https://twitter.com/phxdev"
  status = 300
[[redirects]]
  from = "/links"
  to = "https://linqapp.com/phxdev"
  status = 301
[[redirects]]
  from = "/15"
  to = "https://calendly.com/phxdev/15"
  status = 301
[[redirects]]
  from = "/30"
  to = "https://calendly.com/phxdev/30"
  status = 301
[[redirects]]
  from = "/resources/themeparks/api/*"
  to = "https://steel-wiry-dogwood.glitch.me/:splat"
  status = 200
 [[redirects]]
  from = "/resources/themeparks/docs/*"
  to = "https://phxdev-themeparks.readme.io/:splat"
  status = 200
  
  
  
