[build]
publish = "public"
[[ redirects ]]
  from = "/youtube"
  to = "https://www.youtube.com/phxdev"
  status = 301
[[ redirects ]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/phxdev/"
  status = 301
 [[ redirects ]]
  from = "/twitter"
  to = "https://twitter.com/phxdev"
  status = 300
[[redirects]]
  from = "/links"
  to = "https://beacons.ai/phxdev"
